language: c

compiler:
  - clang
  - gcc

script: 
  - wget "http://nginx.org/download/nginx-1.15.6.tar.gz"
  - git clone https://github.com/yaoweibin/ngx_http_substitutions_filter_module
  - tar xzvf nginx-1.15.6.tar.gz
  - cd nginx-1.15.6
  - ./configure
   --prefix=../nginx-build
   --add-module=../ngx_http_substitutions_filter_module
   --add-module=../
  - make
  - make install
  - echo "
   daemon on;
   worker_processes  1;

   events {
     worker_connections  1024;
   }

   http {
     include       mime.types;
     default_type  application/octet-stream;
     server {
       listen 8080;
       server_name wen.lu;
       resolver 8.8.8.8;
       location / {
         google on;
       }
     }
   }" > ../nginx-build/conf/nginx.conf 
  - ../nginx-build/sbin/nginx -t
  - ../nginx-build/sbin/nginx
  - curl "http://wen.lu" -x 127.0.0.1:8080 -I
